version: '3.8'
services:
  dev-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DB: nest
    networks:
      - database
networks:
  database:
